import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import Providers from '@/lib/Providers/Providers'

const libreBaskerville = Plus_Jakarta_Sans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Acua Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={libreBaskerville.className}>
          <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
        </body>
      </html>
    </Providers>
  )
}
